"""
This file was generated by the tool 'json_to_map.py' in the directory tools.
"""
from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1660, 1122)
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(149, -22),
                    width=163, height=228)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(176, 490),
                    width=138, height=241)
    playground.add(box, box.wall_coordinates)

    # box 2
    box = NormalBox(up_left_point=(650, 451),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)

    # box 3
    box = NormalBox(up_left_point=(670, -319),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # wall 0
    wall = NormalWall(pos_start=(-821, 551),
                      pos_end=(-821, -554))
    playground.add(wall, wall.wall_coordinates)

    # wall 1
    wall = NormalWall(pos_start=(-532, 550),
                      pos_end=(-532, 352))
    playground.add(wall, wall.wall_coordinates)

    # wall 2
    wall = NormalWall(pos_start=(-126, 552),
                      pos_end=(-126, 333))
    playground.add(wall, wall.wall_coordinates)

    # wall 3
    wall = NormalWall(pos_start=(822, 550),
                      pos_end=(822, -553))
    playground.add(wall, wall.wall_coordinates)

    # wall 4
    wall = NormalWall(pos_start=(-530, 551),
                      pos_end=(-530, 353))
    playground.add(wall, wall.wall_coordinates)

    # wall 5
    wall = NormalWall(pos_start=(-820, 550),
                      pos_end=(824, 550))
    playground.add(wall, wall.wall_coordinates)

    # wall 6
    wall = NormalWall(pos_start=(-128, 549),
                      pos_end=(-128, 334))
    playground.add(wall, wall.wall_coordinates)

    # wall 7
    wall = NormalWall(pos_start=(178, 489),
                      pos_end=(178, 253))
    playground.add(wall, wall.wall_coordinates)

    # wall 8
    wall = NormalWall(pos_start=(179, 488),
                      pos_end=(310, 488))
    playground.add(wall, wall.wall_coordinates)

    # wall 9
    wall = NormalWall(pos_start=(308, 488),
                      pos_end=(308, 253))
    playground.add(wall, wall.wall_coordinates)

    # wall 10
    wall = NormalWall(pos_start=(-821, 441),
                      pos_end=(-631, 441))
    playground.add(wall, wall.wall_coordinates)

    # wall 11
    wall = NormalWall(pos_start=(-821, 439),
                      pos_end=(-632, 439))
    playground.add(wall, wall.wall_coordinates)

    # wall 12
    wall = NormalWall(pos_start=(-531, 355),
                      pos_end=(-247, 355))
    playground.add(wall, wall.wall_coordinates)

    # wall 13
    wall = NormalWall(pos_start=(-532, 353),
                      pos_end=(-248, 353))
    playground.add(wall, wall.wall_coordinates)

    # wall 14
    wall = NormalWall(pos_start=(-248, 355),
                      pos_end=(-248, -49))
    playground.add(wall, wall.wall_coordinates)

    # wall 15
    wall = NormalWall(pos_start=(-250, 354),
                      pos_end=(-250, -49))
    playground.add(wall, wall.wall_coordinates)

    # wall 16
    wall = NormalWall(pos_start=(178, 255),
                      pos_end=(309, 255))
    playground.add(wall, wall.wall_coordinates)

    # wall 17
    wall = NormalWall(pos_start=(-821, 253),
                      pos_end=(-631, 253))
    playground.add(wall, wall.wall_coordinates)

    # wall 18
    wall = NormalWall(pos_start=(-821, 251),
                      pos_end=(-632, 251))
    playground.add(wall, wall.wall_coordinates)

    # wall 19
    wall = NormalWall(pos_start=(-388, 240),
                      pos_end=(-388, 79))
    playground.add(wall, wall.wall_coordinates)

    # wall 20
    wall = NormalWall(pos_start=(-390, 239),
                      pos_end=(-390, 79))
    playground.add(wall, wall.wall_coordinates)

    # wall 21
    wall = NormalWall(pos_start=(-530, 81),
                      pos_end=(-389, 81))
    playground.add(wall, wall.wall_coordinates)

    # wall 22
    wall = NormalWall(pos_start=(-532, 232),
                      pos_end=(-532, -32))
    playground.add(wall, wall.wall_coordinates)

    # wall 23
    wall = NormalWall(pos_start=(-126, 193),
                      pos_end=(-126, -151))
    playground.add(wall, wall.wall_coordinates)

    # wall 24
    wall = NormalWall(pos_start=(-128, 192),
                      pos_end=(-128, -151))
    playground.add(wall, wall.wall_coordinates)

    # wall 25
    wall = NormalWall(pos_start=(-622, 155),
                      pos_end=(-622, 73))
    playground.add(wall, wall.wall_coordinates)

    # wall 26
    wall = NormalWall(pos_start=(-624, 154),
                      pos_end=(-624, 73))
    playground.add(wall, wall.wall_coordinates)

    # wall 27
    wall = NormalWall(pos_start=(-530, 233),
                      pos_end=(-530, -31))
    playground.add(wall, wall.wall_coordinates)

    # wall 28
    wall = NormalWall(pos_start=(-531, 79),
                      pos_end=(-388, 79))
    playground.add(wall, wall.wall_coordinates)

    # wall 29
    wall = NormalWall(pos_start=(-821, 75),
                      pos_end=(-623, 75))
    playground.add(wall, wall.wall_coordinates)

    # wall 30
    wall = NormalWall(pos_start=(-821, 73),
                      pos_end=(-622, 73))
    playground.add(wall, wall.wall_coordinates)

    # wall 31
    wall = NormalWall(pos_start=(-821, -15),
                      pos_end=(-630, -15))
    playground.add(wall, wall.wall_coordinates)

    # wall 32
    wall = NormalWall(pos_start=(-821, -17),
                      pos_end=(-631, -17))
    playground.add(wall, wall.wall_coordinates)

    # wall 33
    wall = NormalWall(pos_start=(151, -23),
                      pos_end=(151, -246))
    playground.add(wall, wall.wall_coordinates)

    # wall 34
    wall = NormalWall(pos_start=(152, -24),
                      pos_end=(308, -24))
    playground.add(wall, wall.wall_coordinates)

    # wall 35
    wall = NormalWall(pos_start=(306, -24),
                      pos_end=(306, -246))
    playground.add(wall, wall.wall_coordinates)

    # wall 36
    wall = NormalWall(pos_start=(-531, -29),
                      pos_end=(-386, -29))
    playground.add(wall, wall.wall_coordinates)

    # wall 37
    wall = NormalWall(pos_start=(-532, -31),
                      pos_end=(-387, -31))
    playground.add(wall, wall.wall_coordinates)

    # wall 38
    wall = NormalWall(pos_start=(-622, -133),
                      pos_end=(-622, -299))
    playground.add(wall, wall.wall_coordinates)

    # wall 39
    wall = NormalWall(pos_start=(-624, -134),
                      pos_end=(-624, -299))
    playground.add(wall, wall.wall_coordinates)

    # wall 40
    wall = NormalWall(pos_start=(151, -244),
                      pos_end=(307, -244))
    playground.add(wall, wall.wall_coordinates)

    # wall 41
    wall = NormalWall(pos_start=(-821, -551),
                      pos_end=(823, -551))
    playground.add(wall, wall.wall_coordinates)

    # wall 42
    wall = NormalWall(pos_start=(-623, -299),
                      pos_end=(-816, -299))
    playground.add(wall, wall.wall_coordinates)

    # wall 43
    wall = NormalWall(pos_start=(-623, -296),
                      pos_end=(-820, -296))
    playground.add(wall, wall.wall_coordinates)

    # wall 44
    wall = NormalWall(pos_start=(-628, -173),
                      pos_end=(-674, -173))
    playground.add(wall, wall.wall_coordinates)

    # wall 45
    wall = NormalWall(pos_start=(-818, -170),
                      pos_end=(-764, -170))
    playground.add(wall, wall.wall_coordinates)

    # wall 46
    wall = NormalWall(pos_start=(-818, -173),
                      pos_end=(-764, -173))
    playground.add(wall, wall.wall_coordinates)

    # wall 47
    wall = NormalWall(pos_start=(-674, -170),
                      pos_end=(-628, -170))
    playground.add(wall, wall.wall_coordinates)

    # wall 48
    wall = NormalWall(pos_start=(570, 311),
                      pos_end=(820, 311))
    playground.add(wall, wall.wall_coordinates)

    # wall 49
    wall = NormalWall(pos_start=(570, 71),
                      pos_end=(726, 71))
    playground.add(wall, wall.wall_coordinates)

    # wall 50
    wall = NormalWall(pos_start=(570, 74),
                      pos_end=(570, 206))
    playground.add(wall, wall.wall_coordinates)

    # wall 51
    wall = NormalWall(pos_start=(570, -109),
                      pos_end=(817, -109))
    playground.add(wall, wall.wall_coordinates)

    # wall 52
    wall = NormalWall(pos_start=(570, -303),
                      pos_end=(570, -545))
    playground.add(wall, wall.wall_coordinates)

