"""
This file was generated by the tool 'json_to_map.py' in the directory tools.
"""
from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1200, 900)
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(380, -230),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(-420, -230),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)

    # box 2
    box = NormalBox(up_left_point=(-20, 30),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)

    # box 3
    box = NormalBox(up_left_point=(380, 270),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)

    # box 4
    box = NormalBox(up_left_point=(-420, 270),
                    width=40, height=40)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # wall 0
    wall = NormalWall(pos_start=(-600, 447),
                      pos_end=(599, 447))
    playground.add(wall, wall.wall_coordinates)

    # wall 1
    wall = NormalWall(pos_start=(-600, -447),
                      pos_end=(599, -447))
    playground.add(wall, wall.wall_coordinates)

    # wall 2
    wall = NormalWall(pos_start=(597, -449),
                      pos_end=(597, 450))
    playground.add(wall, wall.wall_coordinates)

    # wall 3
    wall = NormalWall(pos_start=(-597, -449),
                      pos_end=(-597, 450))
    playground.add(wall, wall.wall_coordinates)

    # wall 4
    wall = NormalWall(pos_start=(-498, 350),
                      pos_end=(-352, 350))
    playground.add(wall, wall.wall_coordinates)

    # wall 5
    wall = NormalWall(pos_start=(501, 202),
                      pos_end=(501, 348))
    playground.add(wall, wall.wall_coordinates)

    # wall 6
    wall = NormalWall(pos_start=(-150, 100),
                      pos_end=(151, 100))
    playground.add(wall, wall.wall_coordinates)

    # wall 7
    wall = NormalWall(pos_start=(352, 349),
                      pos_end=(498, 349))
    playground.add(wall, wall.wall_coordinates)

    # wall 8
    wall = NormalWall(pos_start=(-499, 202),
                      pos_end=(-499, 348))
    playground.add(wall, wall.wall_coordinates)

    # wall 9
    wall = NormalWall(pos_start=(-250, 152),
                      pos_end=(-250, 248))
    playground.add(wall, wall.wall_coordinates)

    # wall 10
    wall = NormalWall(pos_start=(250, -248),
                      pos_end=(250, -152))
    playground.add(wall, wall.wall_coordinates)

    # wall 11
    wall = NormalWall(pos_start=(-498, -200),
                      pos_end=(-352, -200))
    playground.add(wall, wall.wall_coordinates)

    # wall 12
    wall = NormalWall(pos_start=(151, -98),
                      pos_end=(151, 98))
    playground.add(wall, wall.wall_coordinates)

    # wall 13
    wall = NormalWall(pos_start=(-500, -348),
                      pos_end=(-500, -202))
    playground.add(wall, wall.wall_coordinates)

    # wall 14
    wall = NormalWall(pos_start=(-150, -98),
                      pos_end=(-150, 98))
    playground.add(wall, wall.wall_coordinates)

    # wall 15
    wall = NormalWall(pos_start=(250, 152),
                      pos_end=(250, 248))
    playground.add(wall, wall.wall_coordinates)

    # wall 16
    wall = NormalWall(pos_start=(500, -202),
                      pos_end=(500, -348))
    playground.add(wall, wall.wall_coordinates)

    # wall 17
    wall = NormalWall(pos_start=(-148, -101),
                      pos_end=(-52, -101))
    playground.add(wall, wall.wall_coordinates)

    # wall 18
    wall = NormalWall(pos_start=(52, -100),
                      pos_end=(148, -100))
    playground.add(wall, wall.wall_coordinates)

    # wall 19
    wall = NormalWall(pos_start=(-98, 299),
                      pos_end=(98, 299))
    playground.add(wall, wall.wall_coordinates)

    # wall 20
    wall = NormalWall(pos_start=(-398, 49),
                      pos_end=(-302, 49))
    playground.add(wall, wall.wall_coordinates)

    # wall 21
    wall = NormalWall(pos_start=(-250, -152),
                      pos_end=(-250, -248))
    playground.add(wall, wall.wall_coordinates)

    # wall 22
    wall = NormalWall(pos_start=(302, 50),
                      pos_end=(398, 50))
    playground.add(wall, wall.wall_coordinates)

    # wall 23
    wall = NormalWall(pos_start=(352, -200),
                      pos_end=(498, -200))
    playground.add(wall, wall.wall_coordinates)

    # wall 24
    wall = NormalWall(pos_start=(-249, 248),
                      pos_end=(-249, 152))
    playground.add(wall, wall.wall_coordinates)

    # wall 25
    wall = NormalWall(pos_start=(-98, 297),
                      pos_end=(98, 297))
    playground.add(wall, wall.wall_coordinates)

    # wall 26
    wall = NormalWall(pos_start=(498, 348),
                      pos_end=(498, 202))
    playground.add(wall, wall.wall_coordinates)

    # wall 27
    wall = NormalWall(pos_start=(302, 44),
                      pos_end=(398, 44))
    playground.add(wall, wall.wall_coordinates)

    # wall 28
    wall = NormalWall(pos_start=(-150, 105),
                      pos_end=(151, 105))
    playground.add(wall, wall.wall_coordinates)

