"""
This file was generated by the tool 'json_to_map.py' in the directory tools.
"""
from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1200, 1200)
def add_boxes(playground):
    # box 0
    box = NormalBox(up_left_point=(-520, -460),
                    width=60, height=60)
    playground.add(box, box.wall_coordinates)

    # box 1
    box = NormalBox(up_left_point=(460, 520),
                    width=60, height=60)
    playground.add(box, box.wall_coordinates)


def add_walls(playground):
    # wall 0
    wall = NormalWall(pos_start=(-280, 150),
                      pos_end=(-280, -30))
    playground.add(wall, wall.wall_coordinates)

    # wall 1
    wall = NormalWall(pos_start=(-435, -110),
                      pos_end=(-380, -110))
    playground.add(wall, wall.wall_coordinates)

    # wall 2
    wall = NormalWall(pos_start=(-380, -110),
                      pos_end=(-380, -175))
    playground.add(wall, wall.wall_coordinates)

    # wall 3
    wall = NormalWall(pos_start=(-435, -265),
                      pos_end=(-325, -265))
    playground.add(wall, wall.wall_coordinates)

    # wall 4
    wall = NormalWall(pos_start=(-435, -30),
                      pos_end=(-280, -30))
    playground.add(wall, wall.wall_coordinates)

    # wall 5
    wall = NormalWall(pos_start=(-520, -300),
                      pos_end=(-520, -110))
    playground.add(wall, wall.wall_coordinates)

    # wall 6
    wall = NormalWall(pos_start=(-520, -30),
                      pos_end=(-520, 150))
    playground.add(wall, wall.wall_coordinates)

    # wall 7
    wall = NormalWall(pos_start=(-520, 230),
                      pos_end=(-520, 430))
    playground.add(wall, wall.wall_coordinates)

    # wall 8
    wall = NormalWall(pos_start=(-520, -380),
                      pos_end=(-435, -380))
    playground.add(wall, wall.wall_coordinates)

    # wall 9
    wall = NormalWall(pos_start=(-380, -440),
                      pos_end=(-380, -520))
    playground.add(wall, wall.wall_coordinates)

    # wall 10
    wall = NormalWall(pos_start=(-280, -520),
                      pos_end=(-70, -520))
    playground.add(wall, wall.wall_coordinates)

    # wall 11
    wall = NormalWall(pos_start=(40, -520),
                      pos_end=(250, -520))
    playground.add(wall, wall.wall_coordinates)

    # wall 12
    wall = NormalWall(pos_start=(-325, -265),
                      pos_end=(-170, -110))
    playground.add(wall, wall.wall_coordinates)

    # wall 13
    wall = NormalWall(pos_start=(-520, 430),
                      pos_end=(-380, 290))
    playground.add(wall, wall.wall_coordinates)

    # wall 14
    wall = NormalWall(pos_start=(-380, 230),
                      pos_end=(-380, 70))
    playground.add(wall, wall.wall_coordinates)

    # wall 15
    wall = NormalWall(pos_start=(-70, -440),
                      pos_end=(-70, -340))
    playground.add(wall, wall.wall_coordinates)

    # wall 16
    wall = NormalWall(pos_start=(-70, -340),
                      pos_end=(40, -340))
    playground.add(wall, wall.wall_coordinates)

    # wall 17
    wall = NormalWall(pos_start=(40, -340),
                      pos_end=(40, -440))
    playground.add(wall, wall.wall_coordinates)

    # wall 18
    wall = NormalWall(pos_start=(-280, -340),
                      pos_end=(-280, -440))
    playground.add(wall, wall.wall_coordinates)

    # wall 19
    wall = NormalWall(pos_start=(-205, -265),
                      pos_end=(-70, -265))
    playground.add(wall, wall.wall_coordinates)

    # wall 20
    wall = NormalWall(pos_start=(-205, -265),
                      pos_end=(-70, -130))
    playground.add(wall, wall.wall_coordinates)

    # wall 21
    wall = NormalWall(pos_start=(130, -210),
                      pos_end=(130, -380))
    playground.add(wall, wall.wall_coordinates)

    # wall 22
    wall = NormalWall(pos_start=(130, -380),
                      pos_end=(300, -380))
    playground.add(wall, wall.wall_coordinates)

    # wall 23
    wall = NormalWall(pos_start=(440, -520),
                      pos_end=(360, -440))
    playground.add(wall, wall.wall_coordinates)

    # wall 24
    wall = NormalWall(pos_start=(440, -520),
                      pos_end=(360, -520))
    playground.add(wall, wall.wall_coordinates)

    # wall 25
    wall = NormalWall(pos_start=(435, 380),
                      pos_end=(520, 380))
    playground.add(wall, wall.wall_coordinates)

    # wall 26
    wall = NormalWall(pos_start=(380, 440),
                      pos_end=(380, 520))
    playground.add(wall, wall.wall_coordinates)

    # wall 27
    wall = NormalWall(pos_start=(520, 300),
                      pos_end=(520, 110))
    playground.add(wall, wall.wall_coordinates)

    # wall 28
    wall = NormalWall(pos_start=(520, 30),
                      pos_end=(520, -150))
    playground.add(wall, wall.wall_coordinates)

    # wall 29
    wall = NormalWall(pos_start=(520, -230),
                      pos_end=(520, -430))
    playground.add(wall, wall.wall_coordinates)

    # wall 30
    wall = NormalWall(pos_start=(520, -430),
                      pos_end=(380, -290))
    playground.add(wall, wall.wall_coordinates)

    # wall 31
    wall = NormalWall(pos_start=(380, -230),
                      pos_end=(380, -70))
    playground.add(wall, wall.wall_coordinates)

    # wall 32
    wall = NormalWall(pos_start=(435, 30),
                      pos_end=(280, 30))
    playground.add(wall, wall.wall_coordinates)

    # wall 33
    wall = NormalWall(pos_start=(280, 26),
                      pos_end=(280, -157))
    playground.add(wall, wall.wall_coordinates)

    # wall 34
    wall = NormalWall(pos_start=(435, 110),
                      pos_end=(380, 110))
    playground.add(wall, wall.wall_coordinates)

    # wall 35
    wall = NormalWall(pos_start=(380, 110),
                      pos_end=(380, 175))
    playground.add(wall, wall.wall_coordinates)

    # wall 36
    wall = NormalWall(pos_start=(325, 265),
                      pos_end=(435, 265))
    playground.add(wall, wall.wall_coordinates)

    # wall 37
    wall = NormalWall(pos_start=(325, 265),
                      pos_end=(170, 110))
    playground.add(wall, wall.wall_coordinates)

    # wall 38
    wall = NormalWall(pos_start=(280, 340),
                      pos_end=(280, 440))
    playground.add(wall, wall.wall_coordinates)

    # wall 39
    wall = NormalWall(pos_start=(280, 520),
                      pos_end=(70, 520))
    playground.add(wall, wall.wall_coordinates)

    # wall 40
    wall = NormalWall(pos_start=(-40, 520),
                      pos_end=(-250, 520))
    playground.add(wall, wall.wall_coordinates)

    # wall 41
    wall = NormalWall(pos_start=(-360, 520),
                      pos_end=(-440, 520))
    playground.add(wall, wall.wall_coordinates)

    # wall 42
    wall = NormalWall(pos_start=(-440, 520),
                      pos_end=(-360, 440))
    playground.add(wall, wall.wall_coordinates)

    # wall 43
    wall = NormalWall(pos_start=(-300, 380),
                      pos_end=(-130, 380))
    playground.add(wall, wall.wall_coordinates)

    # wall 44
    wall = NormalWall(pos_start=(-130, 380),
                      pos_end=(-130, 210))
    playground.add(wall, wall.wall_coordinates)

    # wall 45
    wall = NormalWall(pos_start=(205, 265),
                      pos_end=(70, 265))
    playground.add(wall, wall.wall_coordinates)

    # wall 46
    wall = NormalWall(pos_start=(205, 265),
                      pos_end=(70, 130))
    playground.add(wall, wall.wall_coordinates)

    # wall 47
    wall = NormalWall(pos_start=(70, 340),
                      pos_end=(70, 440))
    playground.add(wall, wall.wall_coordinates)

    # wall 48
    wall = NormalWall(pos_start=(70, 340),
                      pos_end=(-40, 340))
    playground.add(wall, wall.wall_coordinates)

    # wall 49
    wall = NormalWall(pos_start=(-40, 340),
                      pos_end=(-40, 440))
    playground.add(wall, wall.wall_coordinates)

    # wall 50
    wall = NormalWall(pos_start=(-600, 597),
                      pos_end=(599, 597))
    playground.add(wall, wall.wall_coordinates)

    # wall 51
    wall = NormalWall(pos_start=(597, 600),
                      pos_end=(597, -599))
    playground.add(wall, wall.wall_coordinates)

    # wall 52
    wall = NormalWall(pos_start=(-597, 600),
                      pos_end=(-597, -599))
    playground.add(wall, wall.wall_coordinates)

    # wall 53
    wall = NormalWall(pos_start=(-600, -597),
                      pos_end=(599, -597))
    playground.add(wall, wall.wall_coordinates)

