"""
This file was generated by the tool 'json_to_map.py' in the directory tools.
"""
from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1250, 800)
def add_boxes(playground):
    pass


def add_walls(playground):
    # wall 0
    wall = NormalWall(pos_start=(-625, 397),
                      pos_end=(622, 397))
    playground.add(wall, wall.wall_coordinates)

    # wall 1
    wall = NormalWall(pos_start=(-622, 400),
                      pos_end=(-622, -399))
    playground.add(wall, wall.wall_coordinates)

    # wall 2
    wall = NormalWall(pos_start=(-625, -397),
                      pos_end=(622, -397))
    playground.add(wall, wall.wall_coordinates)

    # wall 3
    wall = NormalWall(pos_start=(622, 400),
                      pos_end=(622, -399))
    playground.add(wall, wall.wall_coordinates)

    # wall 4
    wall = NormalWall(pos_start=(-115, 400),
                      pos_end=(-115, -80))
    playground.add(wall, wall.wall_coordinates)

    # wall 5
    wall = NormalWall(pos_start=(285, -399),
                      pos_end=(285, 140))
    playground.add(wall, wall.wall_coordinates)

