"""
This file was generated by the tool 'json_to_map.py' in the directory tools.
"""
from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1113, 750)
def add_boxes(playground):
    pass


def add_walls(playground):
    # wall 0
    wall = NormalWall(pos_start=(-128, 366),
                      pos_end=(-128, 235))
    playground.add(wall, wall.wall_coordinates)

    # wall 1
    wall = NormalWall(pos_start=(-398, 226),
                      pos_end=(-398, -36))
    playground.add(wall, wall.wall_coordinates)

    # wall 2
    wall = NormalWall(pos_start=(554, 375),
                      pos_end=(554, -374))
    playground.add(wall, wall.wall_coordinates)

    # wall 3
    wall = NormalWall(pos_start=(148, 366),
                      pos_end=(148, 235))
    playground.add(wall, wall.wall_coordinates)

    # wall 4
    wall = NormalWall(pos_start=(336, 366),
                      pos_end=(336, 300))
    playground.add(wall, wall.wall_coordinates)

    # wall 5
    wall = NormalWall(pos_start=(150, 139),
                      pos_end=(338, 139))
    playground.add(wall, wall.wall_coordinates)

    # wall 6
    wall = NormalWall(pos_start=(338, 139),
                      pos_end=(338, -109))
    playground.add(wall, wall.wall_coordinates)

    # wall 7
    wall = NormalWall(pos_start=(-302, 136),
                      pos_end=(-132, 136))
    playground.add(wall, wall.wall_coordinates)

    # wall 8
    wall = NormalWall(pos_start=(-130, 135),
                      pos_end=(-130, -275))
    playground.add(wall, wall.wall_coordinates)

    # wall 9
    wall = NormalWall(pos_start=(-436, 114),
                      pos_end=(-400, 114))
    playground.add(wall, wall.wall_coordinates)

    # wall 10
    wall = NormalWall(pos_start=(-300, 12),
                      pos_end=(-300, -226))
    playground.add(wall, wall.wall_coordinates)

    # wall 11
    wall = NormalWall(pos_start=(-130, -107),
                      pos_end=(198, -107))
    playground.add(wall, wall.wall_coordinates)

    # wall 12
    wall = NormalWall(pos_start=(36, -107),
                      pos_end=(36, -275))
    playground.add(wall, wall.wall_coordinates)

    # wall 13
    wall = NormalWall(pos_start=(-548, -142),
                      pos_end=(-400, -142))
    playground.add(wall, wall.wall_coordinates)

    # wall 14
    wall = NormalWall(pos_start=(556, 372),
                      pos_end=(-556, 372))
    playground.add(wall, wall.wall_coordinates)

    # wall 15
    wall = NormalWall(pos_start=(-554, 375),
                      pos_end=(-554, -374))
    playground.add(wall, wall.wall_coordinates)

    # wall 16
    wall = NormalWall(pos_start=(-556, -372),
                      pos_end=(556, -372))
    playground.add(wall, wall.wall_coordinates)

