import argparse
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

from swarm_rescue.tools.map_wall_editor import (
    LINE_WALL,
    RECT_WALL,
    DISPOSAL_CENTER,
    START_AREA,
    WallElement,
    load_elements,
)


def _module_name(name: str) -> str:
    normalized = re.sub(r"[^0-9a-zA-Z]+", "_", name.strip()).strip("_").lower()
    if not normalized:
        raise ValueError("name must contain at least one alphanumeric character")
    if normalized[0].isdigit():
        normalized = f"{normalized}"
    return normalized


def _class_name(module_name: str) -> str:
    return "Map" + "".join(part.capitalize() for part in module_name.split("_") if part)


def _point_to_world(x: int, y: int, width: int, height: int) -> Tuple[int, int]:
    xw = int(round(x - width / 2))
    yw = int(round(-y + height / 2))
    return xw, yw


def _rect_to_world(
    top_left: Tuple[int, int],
    bottom_right: Tuple[int, int],
    width: int,
    height: int,
) -> Tuple[Tuple[int, int], int, int]:
    x0, y0 = top_left
    x1, y1 = bottom_right
    up_left = _point_to_world(x0, y0, width, height)
    return up_left, int(round(x1 - x0)), int(round(y1 - y0))


def _editor_rect_to_center_size_world(
    element: WallElement,
    width: int,
    height: int,
) -> Tuple[int, int, int, int]:
    """
    Map editor pixel rectangle -> (size_w, size_h, center_x_world, center_y_world).

    Sizes match pixel span (same convention as hand-written maps).
    """
    if element.top_left is None or element.bottom_right is None:
        raise ValueError("element must have top_left and bottom_right")
    x0, y0 = element.top_left
    x1, y1 = element.bottom_right
    size_w = max(1, int(round(x1 - x0)))
    size_h = max(1, int(round(y1 - y0)))
    cx_px = (x0 + x1) * 0.5
    cy_px = (y0 + y1) * 0.5
    cx_w, cy_w = _point_to_world(int(round(cx_px)), int(round(cy_px)), width, height)
    return size_w, size_h, cx_w, cy_w


def _write_walls_file(path: Path, width: int, height: int, elements: List[WallElement]) -> None:
    boxes = [element for element in elements if element.element_type == RECT_WALL]
    walls = [element for element in elements if element.element_type == LINE_WALL]

    lines = [
        '"""',
        "This file was generated by the tool 'json_to_map.py' in the directory tools.",
        '"""',
        "from swarm_rescue.simulation.elements.normal_wall import NormalWall, NormalBox",
        "",
        "",
        f"# Dimension of the map : ({width}, {height})",
        "def add_boxes(playground):",
    ]

    if boxes:
        for i, element in enumerate(boxes):
            if element.top_left is None or element.bottom_right is None:
                continue
            up_left, box_width, box_height = _rect_to_world(element.top_left, element.bottom_right, width, height)
            lines.extend(
                [
                    f"    # box {i}",
                    f"    box = NormalBox(up_left_point=({up_left[0]}, {up_left[1]}),",
                    f"                    width={box_width}, height={box_height})",
                    "    playground.add(box, box.wall_coordinates)",
                    "",
                ]
            )
    else:
        lines.extend(["    pass", ""])

    lines.extend(["", "def add_walls(playground):"])
    if walls:
        for i, element in enumerate(walls):
            if element.points is None:
                continue
            start = _point_to_world(element.points[0][0], element.points[0][1], width, height)
            end = _point_to_world(element.points[1][0], element.points[1][1], width, height)
            lines.extend(
                [
                    f"    # wall {i}",
                    f"    wall = NormalWall(pos_start=({start[0]}, {start[1]}),",
                    f"                      pos_end=({end[0]}, {end[1]}))",
                    "    playground.add(wall, wall.wall_coordinates)",
                    "",
                ]
            )
    else:
        lines.extend(["    pass", ""])

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_map_file(
    path: Path,
    module_name: str,
    width: int,
    height: int,
    *,
    start_area_center: Optional[Tuple[int, int]] = None,
    disposal_center_placement: Optional[Tuple[int, int, int, int]] = None,
) -> None:
    class_name = _class_name(module_name)
    if start_area_center is not None:
        start_x, start_y = start_area_center
    else:
        # 默认左下角附近
        margin = max(60, min(width, height) // 8)
        start_x = int(round(-width / 2 + margin))
        start_y = int(round(-height / 2 + margin))

    if disposal_center_placement is not None:
        rescue_width, rescue_height, rescue_x, rescue_y = disposal_center_placement
    else:
        rescue_width = max(40, min(160, width // 7))
        rescue_height = max(40, min(120, height // 6))
        margin = max(20, min(width, height) // 10)
        rescue_x = int(round(width / 2 - margin - rescue_width / 2))
        rescue_y = int(round(-height / 2 + margin + rescue_height / 2))

    text = f"""import gc
import math
import pathlib
import random
import sys
from typing import List, Type

import numpy as np

# Insert the parent directory of the current file's directory into sys.path.
# This allows Python to locate modules that are one level above the current
# script, in this case simulation.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from swarm_rescue.simulation.drone.drone_abstract import DroneAbstract
from swarm_rescue.simulation.drone.drone_motionless import DroneMotionless
from swarm_rescue.simulation.elements.disposal_center import DisposalCenter
from swarm_rescue.simulation.elements.bomb import Bomb
from swarm_rescue.simulation.gui_map.closed_playground import ClosedPlayground
from swarm_rescue.simulation.gui_map.gui_sr import GuiSR
from swarm_rescue.simulation.gui_map.map_abstract import MapAbstract
from swarm_rescue.simulation.reporting.evaluation import EvalConfig, EvalPlan, ZonesConfig
from swarm_rescue.simulation.utils.misc_data import MiscData
from swarm_rescue.simulation.utils.pose import Pose

from swarm_rescue.maps.walls_{module_name} import add_walls, add_boxes


class {class_name}(MapAbstract):

    def __init__(
        self,
        drone_type: Type[DroneAbstract],
        zones_config: ZonesConfig = (),
        number_drones: int | None = None,
    ):
        super().__init__(drone_type, zones_config, number_drones=number_drones)
        self._max_timestep_limit = 7200
        self._max_walltime_limit = 1440  # In seconds

        # PARAMETERS MAP
        self._size_area = ({width}, {height})

        # 无人机出生区域中心点
        self._start_area_drones = ({start_x}, {start_y})

        self._disposal_center = DisposalCenter(size=({rescue_width}, {rescue_height}))
        self._disposal_center_pos = (({rescue_x}, {rescue_y}), 0)

        self._bombs_pos = []
        self._bombs_path = []
        self._number_bombs = len(self._bombs_pos)
        self._bombs: List[Bomb] = []

        # POSITIONS OF THE DRONES
        self._number_drones = self._number_drones_override if self._number_drones_override is not None else 10
        start_area_drones = self._start_area_drones
        nb_per_side = math.ceil(math.sqrt(float(self._number_drones)))
        dist_inter_drone = 40.0
        sx = start_area_drones[0] - (nb_per_side - 1) * 0.5 * dist_inter_drone
        sy = start_area_drones[1] - (nb_per_side - 1) * 0.5 * dist_inter_drone

        self._drones_pos = []
        for i in range(self._number_drones):
            x = sx + (float(i) % nb_per_side) * dist_inter_drone
            y = sy + math.floor(float(i) / nb_per_side) * dist_inter_drone
            angle = random.uniform(-math.pi, math.pi)
            self._drones_pos.append(((x, y), angle))

        self._drones: List[DroneAbstract] = []
        self._playground = ClosedPlayground(size=self._size_area)

        self._playground.add(self._disposal_center, self._disposal_center_pos)

        add_walls(self._playground)
        add_boxes(self._playground)

        self._explored_map.initialize_walls(self._playground)

        # POSITIONS OF THE BOMBS
        for i in range(self._number_bombs):
            bomb = Bomb(disposal_center=self._disposal_center)
            self._bombs.append(bomb)
            init_pos = (self._bombs_pos[i], 0)
            self._playground.add(bomb, init_pos)

            bomb.add_pose_to_path(Pose(np.array(init_pos[0])))
            if i < len(self._bombs_path):
                for pt in self._bombs_path[i]:
                    bomb.add_pose_to_path(Pose(np.array(list(pt))))

        # POSITIONS OF THE DRONES
        misc_data = MiscData(size_area=self._size_area,
                             number_drones=self._number_drones,
                             max_timestep_limit=self._max_timestep_limit,
                             max_walltime_limit=self._max_walltime_limit)
        for i in range(self._number_drones):
            drone = drone_type(identifier=i, misc_data=misc_data)
            self._drones.append(drone)
            self._playground.add(drone, self._drones_pos[i])


def main():
    eval_plan = EvalPlan()
    eval_config = EvalConfig(map_name="{class_name}", zones_config=())
    eval_plan.add(eval_config=eval_config)

    for one_eval in eval_plan.list_eval_config:
        gc.collect()
        map_class = globals().get(one_eval.map_name)
        the_map = map_class(drone_type=DroneMotionless, zones_config=one_eval.zones_config)

        gui = GuiSR(the_map=the_map, use_mouse_measure=True)
        gui.run()


if __name__ == '__main__':
    main()
"""
    path.write_text(text, encoding="utf-8")


def generate_map_from_json(
    *,
    input_json_path: Union[str, Path],
    name: str,
    maps_dir: Union[str, Path] = "src/swarm_rescue/maps",
) -> Dict[str, str]:
    input_json_path = Path(input_json_path)
    maps_dir = Path(maps_dir)
    module_name = _module_name(name)

    with input_json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    canvas = data.get("canvas", {}) or {}
    width = int(canvas.get("width", 1113))
    height = int(canvas.get("height", 750))
    elements = load_elements(data, width=width, height=height)

    maps_dir.mkdir(parents=True, exist_ok=True)

    map_py = maps_dir / f"map_{module_name}.py"
    walls_py = maps_dir / f"walls_{module_name}.py"

    _write_walls_file(walls_py, width, height, elements)

    start_area_el: Optional[WallElement] = None
    disposal_center_el: Optional[WallElement] = None
    for element in reversed(elements):
        if element.element_type == START_AREA and start_area_el is None:
            start_area_el = element
        if element.element_type == DISPOSAL_CENTER and disposal_center_el is None:
            disposal_center_el = element
        if start_area_el is not None and disposal_center_el is not None:
            break

    # 起点区域：只需要中心点坐标（世界坐标），不需要尺寸和 ReturnArea 对象
    start_area_center = None
    if start_area_el is not None and start_area_el.top_left and start_area_el.bottom_right:
        cx_px = (start_area_el.top_left[0] + start_area_el.bottom_right[0]) * 0.5
        cy_px = (start_area_el.top_left[1] + start_area_el.bottom_right[1]) * 0.5
        start_area_center = _point_to_world(int(round(cx_px)), int(round(cy_px)), width, height)

    disposal_center_placement = (
        _editor_rect_to_center_size_world(disposal_center_el, width, height) if disposal_center_el else None
    )

    _write_map_file(
        map_py,
        module_name,
        width,
        height,
        start_area_center=start_area_center,
        disposal_center_placement=disposal_center_placement,
    )

    return {
        "map_py": str(map_py),
        "walls_py": str(walls_py),
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Swarm-Rescue map files from map editor JSON.")
    parser.add_argument("input_json", help="Path to map editor JSON")
    parser.add_argument("--name", required=True, help="Map name, e.g. custom_example")
    parser.add_argument("--maps-dir", default="src/swarm_rescue/maps", help="Directory for generated map Python files")
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    paths = generate_map_from_json(
        input_json_path=args.input_json,
        name=args.name,
        maps_dir=args.maps_dir,
    )
    print(json.dumps(paths, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
